# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-16 08:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uttsavapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCategoryCT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=50)),
                ('event_code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VendingCategoryCT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vending_name', models.CharField(max_length=50)),
                ('vending_code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VendorDetailTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=100)),
                ('vendor_desc', models.CharField(max_length=100)),
                ('vending_category', models.CharField(max_length=100)),
                ('event_category', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='vendorlisttable',
            old_name='event_category',
            new_name='EventCategory',
        ),
        migrations.RenameField(
            model_name='vendorlisttable',
            old_name='vending_category',
            new_name='VendingCategory',
        ),
        migrations.AddField(
            model_name='vendordetailtable',
            name='vendorlisttable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uttsavapp.VendorListTable'),
        ),
    ]
